let randomNumber = parseInt(Math.random() *100 +1)    // 1) "Math.random()": This function in JavaScript returns a floating-point,
                                                        // Essentially, it generates a random decimal number between 0 and just less than 1.
                                                        // 2) "Math.random() * 100": This multiplies the random decimal generated by Math.random() by 100. 
                                                        // So now, you have a random decimal number between 0 and 99.999.....
                                                        // 3) "Math.random() * 100 + 1": By adding 1 to the result of the previous step, you shift the 
                                                        // range of possible values to be between 1 and 100.999...
                                                        // 4) "parseInt()" : This is a function in JavaScript that parses a string argument and returns an integer.
                                                        // When applied to a floating-point number, parseInt() truncates the fractional part, effectively converting 
                                                        // it to an integer. For example, parseInt(3.14) would return 3.
                                                        // 5) "const randomNumber = parseInt(Math.random() * 100 + 1)": Finally, this line combines all the steps above.
                                                        //  It generates a random number between 1 and 100 (inclusive on both ends) and assigns it to the variable
                                                        //  randomNumber.
const submit = document.querySelector('#subt');
const userInput = document.querySelector('#guessField');
const guessSlot = document.querySelector('.guesses');
const remaining = document.querySelector('.lastResult');
const lowOrHi = document.querySelector('.lowOrHi');
const startOver = document.querySelector('.resultParas');

const p = document.createElement('p');

let prevGuess = [];
let numGuess = 1;

let playGame = true;

if (playGame) {
  submit.addEventListener('click', function (e) {
    e.preventDefault();
    const guess = parseInt(userInput.value);
    console.log(guess);
    validateGuess(guess);
  });
}

function validateGuess(guess) {
  if (isNaN(guess)) {
    alert('PLease enter a valid number');
  } else if (guess < 1) {
    alert('PLease enter a number more than 1');
  } else if (guess > 100) {
    alert('PLease enter a  number less than 100');
  } else {
    prevGuess.push(guess);
    if (numGuess === 11) {
      displayGuess(guess);
      displayMessage(`Game Over. Random number was ${randomNumber}`);
      endGame();
    } else {
      displayGuess(guess);
      checkGuess(guess);
    }
  }
}


function checkGuess(guess) {
  if (guess === randomNumber) {
    displayMessage(`You guessed it right`);
    endGame();
  } else if (guess < randomNumber) {
    displayMessage(`Number is TOOO low`);
  } else if (guess > randomNumber) {
    displayMessage(`Number is TOOO High`);
  }
}

function displayGuess(guess) {
  userInput.value = '';
  guessSlot.innerHTML += `${guess}, `;
  numGuess++;
  remaining.innerHTML = `${11 - numGuess} `;
}

function displayMessage(message) {
  lowOrHi.innerHTML = `<h2>${message}</h2>`;
}

function endGame() {
  userInput.value = '';
  userInput.setAttribute('disabled', '');
  p.classList.add('button');
  p.innerHTML = `<h2 id="newGame">Start new Game</h2>`;
  startOver.appendChild(p);
  playGame = false;
  newGame();
}


function newGame() {
  const newGameButton = document.querySelector('#newGame');
  newGameButton.addEventListener('click', function (e) {
    randomNumber = parseInt(Math.random() * 100 + 1);
    prevGuess = [];
    numGuess = 1;
    guessSlot.innerHTML = '';
    remaining.innerHTML = `${11 - numGuess} `;
    userInput.removeAttribute('disabled');
    startOver.removeChild(p);

    playGame = true;
  });
}